version: '3.8'

services:
  myapp:
    image: myapp:latest
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "HML"
    volumes:
      - /home/natan/appsettings/appsettings.json Tech.Challenge.I/appsettings.json:/app/appsettings.json