name: .NET Build, Unit, and Integration Tests, and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore path/to/your-solution.sln

    - name: Build the project
      run: dotnet build path/to/your-solution.sln --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test path/to/your-solution.sln --no-build --configuration Release --filter Category!=Integration --logger "trx;LogFileName=unit-test-results.trx"

    - name: Run integration tests
      run: dotnet test path/to/your-solution.sln --no-build --configuration Release --filter Category=Integration --logger "trx;LogFileName=integration-test-results.trx"

    - name: Publish the project
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
      run: dotnet publish path/to/your-solution.sln --no-build --configuration Release --output ${{ github.workspace }}/publish

    - name: Upload artifact
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/publish
